# Generated by Django 4.1.7 on 2023-04-28 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_services_alter_news_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Services',
        ),
    ]
